### PR TITLE
Add Ancient to GameMap

### PR DESCRIPTION
**Pull request by c9win**
Add in Ancient to the GameMap file #472

### CODE REVIEW

**Comment by gigobyte** [comment]
Thanks for the contribution, I'm quite busy so I couldn't spend time doing it myself.

**Comment by c9win** [comment]
No problem! Sorry to ask as I'm sure how long this takes you or what the process is, but, would it be possible to push an update so I can pull this fix into my app? Thanks gigobyte. This repo has been an incredible tool.

**Comment by gigobyte** [comment]
Yeah, sorry, forgot. It's released now.

**Comment by c9win** [comment]
Appreciate you @gigobyte!

**Pull request merged**
