### PR TITLE
improvement of getMatches filter

### PR DESCRIPTION
**Pull request by Revilum**
although HLTV doesn't provide a filter on the hltv.org/matches for teams, adding `?Team=teamid` filters all upcoming after the teams. It also works for selecting multiple events.

### CODE REVIEW

**Comment by gigobyte** [comment]
Please fix the formatting and remove the changes to playground.

**Comment by Revilum** [comment]
done

**Comment by gigobyte** [comment]
When I click an event icon it actually generates this url: `https://www.hltv.org/matches?event=6137`. Shouldn't we be using event instead of eventId(s)?

**Comment by Revilum** [comment]
you can select multiple events so Ids would be correct? the filter/url attribute works the same as the events filter for gerResults

**Comment by gigobyte** [comment]
Oh sorry, I misread the code.

**Pull request merged**
