### PR TITLE
Added another module "getResultsDemo"

### PR DESCRIPTION
**Pull request by Kaszanas**
Expanding the functionality to be able to filter only the results with the demos attached without the need to go through all the records of results which might not have one attached.

### CODE REVIEW

**Comment by Kaszanas** [comment]
Added getResultsDemo to be able to parse only the results that have demos attached. Expanding the opportunity to automatically reach demos.

**Comment by gigobyte** [comment]
This is better as a flag to the `getResults` method, it's basically a parameter to the url, everything else is the same.

**Comment by Kaszanas** [comment]
Yes I know.
I must say that I am very unexperienced. If You'd show me through how to
commit such changes as "flags" so that they will be included. I'd be happy
to do it.
I have no official experience in programming I am just looking for
additional functionality and I have found another one that might be used as
the one before.

sob., 16 mar 2019 o 09:15 Stanislav Iliev <notifications@github.com>
napisał(a):

**Comment by Kaszanas** [comment]
Okay I will try to edit the TypeScript files to be able to add another argument to the functions being used to expand the functionality after that I will try ro be back with another pull request :)
👍

**Pull request closed without merging**
