### PR TITLE
Adding the MatchStatsId to the getMatch request

### PR DESCRIPTION
**Pull request by honjes**
#206

### CODE REVIEW

**Comment by gigobyte** [comment]
Looks good, but you need to merge master into your fork, it's outdated.

**Comment by honjes** [comment]
Is that doing it ?

**Comment by gigobyte** [comment]
You can run the tests by typing `yarn test` in your command line. In your case `yarn test getMatch.test` will run only the getMatch tests. Currently they fail because your code crashes on this match:

https://www.hltv.org/matches/2290099/-

**Comment by honjes** [comment]
Hey i having a problem with the Test could you take a look at it?
I didn't changed anything what shuld cause the test too fail there.

**Comment by gigobyte** [comment]
Well it fails on the match I sent you in my previous comment (https://www.hltv.org/matches/2290099/-), because it doesn't have the `.stats-detailed-stats` element

**Comment by honjes** [comment]
Is there still somthing i have overlooked or is it good ?

**Comment by gigobyte** [comment]
It's good, I'll merge the PR today.

**Pull request merged**
